:SPCFUNC VarOrVal1 is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=0 {
	spcfunc(VarOrVal1);
}
:SPCFUNC VarOrVal1,(VarOrVal3) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=1;VarOrVal3 {
	spcfunc(VarOrVal1,VarOrVal3);
}
:SPCFUNC VarOrVal1,(VarOrVal3,VarOrVal4) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=2;VarOrVal3;VarOrVal4 {
	spcfunc(VarOrVal1,VarOrVal3,VarOrVal4);
}
:SPCFUNC VarOrVal1,(VarOrVal3,VarOrVal4,VarOrVal5) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=3;VarOrVal3;VarOrVal4;VarOrVal5 {
	spcfunc(VarOrVal1,VarOrVal3,VarOrVal4,VarOrVal5);
}
:SPCFUNC VarOrVal1,(VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=4;VarOrVal3;VarOrVal4;VarOrVal5;VarOrVal6 {
	spcfunc(VarOrVal1,VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6);
}
:SPCFUNC VarOrVal1,(VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=5;VarOrVal3;VarOrVal4;VarOrVal5;VarOrVal6;VarOrVal7 {
	spcfunc(VarOrVal1,VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7);
}
:SPCFUNC VarOrVal1,(VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7,VarOrVal8) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=6;VarOrVal3;VarOrVal4;VarOrVal5;VarOrVal6;VarOrVal7;VarOrVal8 {
	spcfunc(VarOrVal1,VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7,VarOrVal8);
}
:SPCFUNC VarOrVal1,(VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7,VarOrVal8,VarOrVal9) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=7;VarOrVal3;VarOrVal4;VarOrVal5;VarOrVal6;VarOrVal7;VarOrVal8;VarOrVal9 {
	spcfunc(VarOrVal1,VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7,VarOrVal8,VarOrVal9);
}
:SPCFUNC VarOrVal1,(VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7,VarOrVal8,VarOrVal9,VarOrVal10) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=8;VarOrVal3;VarOrVal4;VarOrVal5;VarOrVal6;VarOrVal7;VarOrVal8;VarOrVal9;VarOrVal10 {
	spcfunc(VarOrVal1,VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7,VarOrVal8,VarOrVal9,VarOrVal10);
}
:SPCFUNC VarOrVal1,(VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7,VarOrVal8,VarOrVal9,VarOrVal10,VarOrVal11) is AdcOp & op_lsb=0x7A; VarOrVal1;VarOrVal2 & idx9=9;VarOrVal3;VarOrVal4;VarOrVal5;VarOrVal6;VarOrVal7;VarOrVal8;VarOrVal9;VarOrVal10;VarOrVal11 {
	spcfunc(VarOrVal1,VarOrVal3,VarOrVal4,VarOrVal5,VarOrVal6,VarOrVal7,VarOrVal8,VarOrVal9,VarOrVal10,VarOrVal11);
}
