CharEnd1: is str8=0x00 { export 0x00:1; }
CharEnd2: is str8=0x00 { export 0x00:1; }
CharEnd3: is str8=0x00 { export 0x00:1; }
CharEnd4: is str8=0x00 { export 0x00:1; }
CharEnd5: is str8=0x00 { export 0x00:1; }
CharEnd6: is str8=0x00 { export 0x00:1; }

Char1: Char is Char { export Char; }
Char2: Char is Char { export Char; }
Char3: Char is Char { export Char; }
Char4: Char is Char { export Char; }
Char5: Char is Char { export Char; }
Char6: Char is Char { export Char; }
Char7: Char is Char { export Char; }
Char8: Char is Char { export Char; }
Char9: Char is Char { export Char; }
Char10: Char is Char { export Char; }
Char11: Char is Char { export Char; }
Char12: Char is Char { export Char; }
Char13: Char is Char { export Char; }
Char14: Char is Char { export Char; }
Char15: Char is Char { export Char; }
Char16: Char is Char { export Char; }
Char17: Char is Char { export Char; }
Char18: Char is Char { export Char; }
Char19: Char is Char { export Char; }
Char20: Char is Char { export Char; }
Char21: Char is Char { export Char; }
Char22: Char is Char { export Char; }
Char23: Char is Char { export Char; }
Char24: Char is Char { export Char; }
Char25: Char is Char { export Char; }
Char26: Char is Char { export Char; }
Char27: Char is Char { export Char; }
Char28: Char is Char { export Char; }
Char29: Char is Char { export Char; }
Char30: Char is Char { export Char; }
Char31: Char is Char { export Char; }
Char32: Char is Char { export Char; }
Char33: Char is Char { export Char; }
Char34: Char is Char { export Char; }
Char35: Char is Char { export Char; }
Char36: Char is Char { export Char; }
Char37: Char is Char { export Char; }
Char38: Char is Char { export Char; }
Char39: Char is Char { export Char; }
Char40: Char is Char { export Char; }
Char41: Char is Char { export Char; }
Char42: Char is Char { export Char; }
Char43: Char is Char { export Char; }
Char44: Char is Char { export Char; }
Char45: Char is Char { export Char; }
Char46: Char is Char { export Char; }
Char47: Char is Char { export Char; }
Char48: Char is Char { export Char; }
Char49: Char is Char { export Char; }
Char50: Char is Char { export Char; }
Char51: Char is Char { export Char; }
Char52: Char is Char { export Char; }
Char53: Char is Char { export Char; }
Char54: Char is Char { export Char; }
Char55: Char is Char { export Char; }
Char56: Char is Char { export Char; }
Char57: Char is Char { export Char; }
Char58: Char is Char { export Char; }
Char59: Char is Char { export Char; }
Char60: Char is Char { export Char; }
Char61: Char is Char { export Char; }
Char62: Char is Char { export Char; }
Char63: Char is Char { export Char; }
Char64: Char is Char { export Char; }
Char65: Char is Char { export Char; }
Char66: Char is Char { export Char; }
Char67: Char is Char { export Char; }
Char68: Char is Char { export Char; }
Char69: Char is Char { export Char; }
Char70: Char is Char { export Char; }
Char71: Char is Char { export Char; }
Char72: Char is Char { export Char; }
Char73: Char is Char { export Char; }
Char74: Char is Char { export Char; }
Char75: Char is Char { export Char; }
Char76: Char is Char { export Char; }
Char77: Char is Char { export Char; }
Char78: Char is Char { export Char; }
Char79: Char is Char { export Char; }
Char80: Char is Char { export Char; }


@include "str_ascii1.inc"
@include "str_ascii2.inc"
