Var: (loc) is var4=0xC & idx9 [ loc = 0x0100C000 + idx9*2; ] { export *:2 loc; }
Var: (loc) is var4=0xD & idx9 [ loc = 0x0100D000 + idx9*2; ] { export *:2 loc; }
Var: (loc) is var4=0xE & idx9 [ loc = 0x0100E000 + idx9*2; ] { export *:2 loc; }
Var: (loc) is var4=0xF & idx9 [ loc = 0x0100F000 + idx9*2; ] { export *:2 loc; }
Var: (loc) is var4=0x0 & idx9 [ loc = 0x0100D000 + idx9*2; ] { export *:2 loc; }

Var1: Var  is Var { export Var; }
Var2: Var  is Var { export Var; }
Var3: Var  is Var { export Var; }
Var4: Var  is Var { export Var; }
Var5: Var  is Var { export Var; }
Var6: Var  is Var { export Var; }
Var7: Var  is Var { export Var; }
Var8: Var  is Var { export Var; }
