VarOrVal:  Var      is Var             { export Var; }
VarOrVal:  imm16     is var4=0x0 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x1 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x2 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x3 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x4 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x5 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x6 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x7 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x8 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0x9 & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0xA & imm16 { c:2 = imm16; export c; }
VarOrVal:  imm16     is var4=0xB & imm16 { c:2 = imm16; export c; }
VarOrVal1: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal2: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal3: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal4: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal5: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal6: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal7: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal8: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal9: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal10: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal11: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal12: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal13: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal14: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal15: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal16: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal17: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal18: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal19: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal20: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal21: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal22: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal23: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal24: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal25: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal26: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal27: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal28: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal29: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal30: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal31: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal32: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal33: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal34: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal35: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal36: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal37: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal38: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal39: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal40: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal41: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal42: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal43: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal44: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal45: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal46: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal47: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal48: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal49: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal50: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal51: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal52: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal53: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal54: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal55: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal56: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal57: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal58: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal59: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal60: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal61: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal62: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal63: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal64: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal65: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal66: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal67: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal68: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal69: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal70: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal71: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal72: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal73: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal74: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal75: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal76: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal77: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal78: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal79: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal80: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal81: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal82: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal83: VarOrVal is VarOrVal        { export VarOrVal; }
VarOrVal84: VarOrVal is VarOrVal        { export VarOrVal; }